=== SvenPeldszus/emoflon-tool/org.moflon.tutorial/cheatSheetFormat.dtd
<!ELEMENT cheatsheet (intro , item+)>

<!ATTLIST cheatsheet
title CDATA #REQUIRED
>

<!ELEMENT intro (description)>

<!ATTLIST intro
contextId CDATA #IMPLIED
href      CDATA #IMPLIED
>

<!ELEMENT b (#PCDATA | br)*>
<!ELEMENT br EMPTY>
<!ELEMENT description (#PCDATA | b | br)*>

<!ELEMENT item (description , (action | command | perform-when | (subitem | conditional-subitem | repeated-subitem)*) , onCompletion?)>

<!ATTLIST item
title     CDATA #REQUIRED
validation CDATA #IMPLIED
dialog    (true | false) "false"
skip      (true | false) "false"
contextId CDATA #IMPLIED
href      CDATA #IMPLIED
>

<!ELEMENT subitem (description? , (action | command | perform-when)?)>

<!ATTLIST subitem
label CDATA #REQUIRED
skip  (true | false) "false"
when  CDATA #IMPLIED
>

<!ELEMENT conditional-subitem (subitem+)>

<!ATTLIST conditional-subitem
condition CDATA #REQUIRED
>

<!ELEMENT repeated-subitem (subitem)>

<!ATTLIST repeated-subitem
values CDATA #REQUIRED
>

<!ELEMENT action EMPTY>

<!ATTLIST action
class     CDATA #REQUIRED
pluginId  CDATA #REQUIRED
param1    CDATA #IMPLIED
param2    CDATA #IMPLIED
param3    CDATA #IMPLIED
param4    CDATA #IMPLIED
param5    CDATA #IMPLIED
param6    CDATA #IMPLIED
param7    CDATA #IMPLIED
param8    CDATA #IMPLIED
param9    CDATA #IMPLIED
confirm   (true | false) "false"
when      CDATA #IMPLIED
required  (true | false) "true"
translate CDATA #IMPLIED
>

<!ELEMENT command EMPTY>

<!ATTLIST command
serialization CDATA #REQUIRED
returns       CDATA #IMPLIED
confirm       (true | false) "false"
when          CDATA #IMPLIED
required      (true | false) "true"
translate     CDATA #IMPLIED
>

<!ELEMENT onCompletion (#PCDATA | b | br)*>

<!ELEMENT perform-when (action | command)+>

<!ATTLIST perform-when
condition CDATA #REQUIRED
>

=== SvenPeldszus/emoflon-tool/org.moflon.tutorial/Chapter2 SDM.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cheatsheet SYSTEM "cheatSheetFormat.dtd">
<cheatsheet title="Chapter 2: SDM">
	<intro>
    	<description>
         In this Chapter, you'll learn about Story Driven Modeling (SDM). For the
         interested reader, the content of this chapter is based on Part III of the 
         eMoflon handbook.<br/>
         
         <br/>
         To briefly explain, SDMs implement unidirectional model transformations. They're
         a combination of simplified activity diagrams and graph pattern rules used to
         describe behaviour. In other words, SDMs can be used to specify a language's dynamic semantics.
         <br/>
         
         <br/>
         We'll start the chapter by modeling what <b>Board</b> can do, specifically how it
         will handle clearing all Floors of their Figures, and selecting Figures for
         action. We'll then proceed to describe how each Figure moves. Let's begin!
      </description>
	</intro>
<item 
		title="Step 1 - Figure.moveTo()">
		<description>
      	 To ease ourselves into SDM patterns, let's update the moveTo method in 
      	 <b>Figure</b> by implementing a simple control flow:<br/>
         
         <br/>
         <b> moveTo(floor : Floor) : void { </b><br/>
         <b> &#160;&#160;&#160;&#160;&#160; if [moveFigure] </b><br/>
         <b> &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; return </b><br/>
         <b> &#160;&#160;&#160;&#160;&#160; </b><br/>
         <b> } </b>  <br/>
                            
         <br/>
         This method invokes the 'moveFigure pattern', which handles actual details
         of the method in a separate file containing the pattern.
         We consider this pattern
         to be the fundamental movement of any figure type, to be customized for
         each figure's specific actions (such as allowing the Admin to push
         Servers, or making Wall immobile).
         <br/>
         
         <br/>
         Save the file. Some errors should immediately appear in the 'Problems' tab 
         below the editor - MOSL complains that it is unable to find the pattern file.
         Select this error, and press <b>Ctrl + 1</b> to invoke a "Quick Fix" dialogue.
         
         <br/>
         This window offers to generate the missing file for you. Select the fix, then press 
         finish. The new file should open automatically in the editor. We'll complete it in 
         the next step.
      </description>
	<action class = "org.moflon.tutorial.actions.CopyResourceToProject" pluginId = "org.moflon.CheatSheetTutorial"
         required = "false"
      param1 = "resources/tutorial-Sokoban/Chapter2/Step01"
      param2 = "SokobanTutorial/MOSL/MyWorkingSet/SokobanLanguage"
      param3 = "nobuild"/>>
   </item>
   
<item
	  title="Step 2 - moveFigure.pattern">
      <description>
    	Before editing your pattern, take a look at your Package Explorer. When you
    	first created the <b>SokobanLanguage</b> EPackage, a <b>_patterns</b> folder was 
    	automatically created with it. This folder will contain subfolders for each
    	class that contains a method with a pattern, which will, in turn, store the
    	actual pattern file. <br/>
    	
    	<br/>
		A pattern is basically a set of constraints. It defines various object and link
		variables, and each variable scope can state constraints on its attributes and references
		as defined in its class. Add the following object variables:
		<br/>
		
		<br/><b> oldFloor : Floor</b><br/>

		<br/><b> @floor : Floor </b><br/>
		
		<br/>
		The first is a temporary free object variable. The second variable is bound (indicated by the "@" sign)
		the parameter value 'floor,' which represents 
		the target floor space the figure is trying to move to.
		<br/>
		
		<br/>
		Next, create an object variable that matches to the invoking figure:<br/>
		
		<br/><b> @this : Figure</b><br/>
		
		<br/>
		Let's add a scope to this variable to handle the 'floor' reference connecting it some
		valid Floor instance. Update '@this' until it resembles:<br/>
		
		<br/>
		<b> @this : Figure { </b><br/>
		<b> &#160;&#160;&#160;&#160;&#160;--  -floor-> oldFloor </b><br/>
		<b> &#160;&#160;&#160;&#160;&#160;++  -floor-> floor </b><br/>
		<b> } </b><br/>
		
		<br/>
		As you can see, we REMOVE the reference to the Figure's current Floor, and ADD a new reference to
		the target floor.<br/>
		
		<br/>
		Press "Click to Perform" to load a commented 'moveFigure.pattern' into your workspace which will
		explain patterns and their variables in more detail. Otherwise, save, build, and proceed to Step 3.
	</description>
	 <action class = "org.moflon.tutorial.actions.CopyResourceToProject" pluginId = "org.moflon.CheatSheetTutorial"
         required = "false"
      param1 = "resources/tutorial-Sokoban/Chapter2/Step02"
      param2 = "SokobanTutorial/MOSL/MyWorkingSet/SokobanLanguage/_patterns/Figure/moveTo"/>
   </item>
<item
         title="Step 3 - Board.floorSelected()"
         validation="chapter2;1">
      <description>
      	Even though we&apos;ve implemented how a Figure will move between floors, we haven&apos;t implemented the 
      	<b>floorSelected</b> method of our <b>Board</b> so that the game actually &apos;activates&apos;
      	the relevant Figure.<br/>
      	
      	<br/>
      	This method must first check to see if a Figure has been selected. If one has, move that figure 
      	to the target via the moveTo method we established in Step 1 and 2. 
      	Otherwise, if a Figure has not yet been selected, select it! <br/>
		
		<br/>
		This method will need two patterns - one to check for a Figure, and one to select a Figure.
		It will also need an if/else control flow.<br/>
		
		<br/>
		Open &apos;Board&apos; and implement the &apos;floorSelected&apos; method as described below. Don&apos;t
		forget about eMoflon&apos;s auto-completion feature! You can use it here to generate a template.<br/>
		
		<br/>
		<b> floorSelected(floor : Floor) : void {</b><br/>
		<b>       if [checkSelected] { </b><br/>
		<b>          &lt;@alreadySelectedFigure.moveTo($floor)&gt; </b><br/>
		<b>       } else { </b><br/>
		<b>          if [selectFigure] { </b><br/>
		<b>               return</b><br/>
		<b>          } </b><br/>
		<b>       } </b><br/>
		<b>       return </b><br/>
		<b> } </b><br/>
		
		<br/>
		As you can see, the moveTo method call is NOT implemented as a pattern. In fact, MOSL doesn&apos;t 
		allow direct method calls. Instead, it uses statement nodes and syntax similar to Java to 
		permit communication between classes.<br/>
		
		<br/>
		Save your project and build the two new patterns or press <b>Click to perform</b> below to 
		load an updated and commented &apos;Board.eclass&apos; file with more details about method control and 
		statement nodes. Don&apos;t worry about the error message that remains after creating the patterns 
		- the next step will take care of this.
   	</description>
	<action class = "org.moflon.tutorial.actions.CopyResourceToProject" pluginId = "org.moflon.CheatSheetTutorial"
         required = "false"
      param1 = "resources/tutorial-Sokoban/Chapter2/Step03"
      param2 = "SokobanTutorial/MOSL/MyWorkingSet/SokobanLanguage"
      param3 = "nobuild"/>>
   </item>
<item
         title="Step 4 - checkSelected.pattern">
      <description>
		Open <b>checkSelected.pattern</b>. This is the pattern that checks to see if a reference
		to a Figure already exists. You'll need two object variables, one for the figure, and one
		for the invoking board. Complete your pattern as written below:<br/>
		
		<br/> <b>alreadySelectedFigure : Figure </b><br/>

		<br/><b>@this : Board { </b><br/>
		<b>	&#160;&#160;&#160;&#160;&#160;-- -selectedFigure-> alreadySelectedFigure </b><br/>
		<b>}</b><br/>
		
		<br/>
		This pattern attempts to remove the 'selectedFigure' reference to a Figure. If this fails
		(i.e., if there is no reference to remove), then no figure has obviously been selected, and the
		if/else in board.fieldSelected will proceed to the second pattern. If this passes, the
		control flow proceeds to the statement node.
  </description>
	 <action class = "org.moflon.tutorial.actions.CopyResourceToProject" pluginId = "org.moflon.CheatSheetTutorial"
         required = "false"
      param1 = "resources/tutorial-Sokoban/Chapter2/Step04"
      param2 = "SokobanTutorial/MOSL/MyWorkingSet/SokobanLanguage/_patterns/Board/floorSelected"
      param3 = "nobuild"/>>
   </item>
<item
     title="Step 5 - selectFigure.pattern">
     <description>
   		Given that this pattern is reached when no figure is currently active, we need to set
   		the 'selectedFigure' reference for Board, determining the relevant Figure instance
   		by matching the 'figure' reference for Floor. Complete your pattern as described below:
   		<br/>
   		
		<br/><b> @floor : Floor { </b><br/>
		<b>	&#160;&#160;&#160;&#160;&#160; -figure-> figure </b><br/>
		<b> } </b>
		<br/><br/>
		<b> @this : Board { </b><br/>
		<b>	&#160;&#160;&#160;&#160;&#160; ++ -selectedFigure-> figure </b><br/>
		<b> } </b><br/>
		
		<br/><b>figure : Figure </b><br/>
		
		<br/>
		That's everything you needed for Board.fieldSelected(floor:Floor)! Save and build your
		project now to confirm everything has been done correctly.
     </description>
      <action class = "org.moflon.tutorial.actions.CopyResourceToProject" pluginId = "org.moflon.CheatSheetTutorial"
         required = "false"
      param1 = "resources/tutorial-Sokoban/Chapter2/Step05"
      param2 = "SokobanTutorial/MOSL/MyWorkingSet/SokobanLanguage/_patterns/Board/floorSelected"/>>
</item>
<item
     	title="Step 6 - Board.clear()"
     	validation="chapter2;5">
     <description>
